### ISSUE TITLE
DTMF Decode

### ISSUE THREAD

**Issue by spm81** [OneOfEleven/uv-k5-firmware-custom#10]
DTMF Decode works with QuanShang radio but with baofeng for exemple don't decode all characters.

Keep the good job ;)

**Comment by OneOfEleven** [comment]
mmm you're right, never knew that. The QS firmware must be the same too, I'll look at the DTMF settings to the radio chip, although we don't have a detailed data sheet for this radios chip :(

**Comment by OneOfEleven** [comment]
There are 16 DTMF coefficient values that the firmware sets in the BK4819 radio chip, knowing what exactly they do and how best to adjust them I'm sure would fix the DTMF decoder.

However, we don't have that info, we need detailed info on the chips registers (we have bits of info but not all) :(

**Comment by lohtse** [comment]
could you add this to makefile please 

 ENABLE_DTMF_DECODER l=0 

see in group for the reason why

**Comment by OneOfEleven** [comment]
What groups that ?

**Comment by OneOfEleven** [comment]
??

I don't use telegram

**Comment by lohtse** [comment]
![image](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/48331155/e6ffb9ef-70c7-4b5e-bdba-219fd4d44b88)

**Comment by lohtse** [comment]
when dtmf is enable it prints out link that for some when using repeaters.. no issue when disable

**Comment by OneOfEleven** [comment]
The DTMF decoder is now enabled/disabled in the menu, look for "D-LIVE"

**Comment by lohtse** [comment]
ar ok

**Comment by OneOfEleven** [comment]
> DTMF Decode works with QuanShang radio but with baofeng for exemple don't decode all characters.
> 
> Keep the good job ;)

I've tuned the DTMF decoder a bit, it now works with the wuoxun radio I have here, maybe you can try the decoder with your other radios ? .. let me know how it goes if you do

**Comment by spm81** [comment]
The DTMF decoder is now enabled/disabled in the menu, look for "D-LIVE"

D-LIVE is ON but nothing appeared :(((

**Comment by OneOfEleven** [comment]
Have you the ENABLE_AUDIO_BAR set to '1' ?

If so, set it to '0' to disable it, recompile, or disable the MIC bar menu option. The displays center line can only be used one or the other function. Also have to be in FM mode.

**Comment by spm81** [comment]
ok , i see... i will try it and send you a feedback later ... thanks..... a lot :)

**Comment by spm81** [comment]
i disable MIC bar option and DTMF decoder worked :)))))))))))))
I try with the Baofeng UV-5R again and.................... ALL KEYS WORKING 🥇 
Thanks once again..... Keep the good job 💯 %

**Comment by OneOfEleven** [comment]
Good good, was interested to know if it now works OK for anyone else.
