### ISSUE TITLE
Strange behaviuor of squelch, commit bf2564b

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#100]
Strange behaviuor of squelch on  commit bf2564b.
Compiled with standard squelch. Squelch set quite high (value 4) in a silent environment
Green led blinks shortly and randomly very often without squelch opening. 
Previoulsly value 4 ensured complete muting

**Comment by bricky149** [comment]
Are you using the squelch_lower option? I've found it can open squelch too keenly, perhaps due to the noise threshold.

**Comment by pawol** [comment]
like I wrote - standard squelch

**Comment by bricky149** [comment]
> like I wrote - standard squelch. I suspect auto bandwidth for small signals/ sensitivity mechanism you applied last time

My apologies for misunderstanding.

The issue you describe was one I experienced before that change. For me it was down to squelch, I'm not sure what your case might be.

**Comment by OneOfEleven** [comment]
I have made the squelch more sensitive, not just in level but also in time, ie it opens/closes faster than before - to let me increase channel scan speed.

**Comment by pawol** [comment]
green led blinks and backlight lits also. So, it is quite bad feature

**Comment by OneOfEleven** [comment]
OK, I could add a time constant to the backlight so that it only comes on if the squelch remains open for a set time.

I've added a new option to enable/disable faster scanning - this also controls the faster squelch which causes the LED to be twitchy. See how things go with faster scanning disabled.

**Comment by pawol** [comment]
The question is... how often you use scanning and how often you get angry because of self liting background and green led.

**Comment by OneOfEleven** [comment]
My radio is always on channel scan.

**Comment by pawol** [comment]
If it is an option then OK. By default that behaviour is bad an annoying :)

**Comment by pawol** [comment]
I confirm that when fast scanning option is disabled then standard squelch works as expected. The ticket can be closed
