### ISSUE TITLE
Can't Select COMPANDER on the menu

### ISSUE THREAD

**Issue by spm81** [OneOfEleven/uv-k5-firmware-custom#101]
Can't Select COMPANDER on the menu

**Comment by OneOfEleven** [comment]
Do you mean it's not there or that you can't change it's value ?

**Comment by spm81** [comment]
the menu is there... but changes dont save...

**Comment by OneOfEleven** [comment]
It was saving the setting in VFO mode, but not in channel mode.

Think I've fixed it.

**Comment by spm81** [comment]
Thanks a lot 🥇
