### ISSUE TITLE
F7 band locked to .600

### ISSUE THREAD

**Issue by Yag00000** [OneOfEleven/uv-k5-firmware-custom#102]
F7 band locked to .600

**Comment by OneOfEleven** [comment]
Try it now, found a bug I made when changing to a simpler frequency band table yesterday.

**Comment by pawol** [comment]
I confirm. Cannot put  eg. 470 MHz into VFO

**Comment by OneOfEleven** [comment]
I can

**Comment by OneOfEleven** [comment]
This isn't egzumers firmware repo though

**Comment by pawol** [comment]
OK. He is behind you a few commits

**Comment by lohtse** [comment]
> This isn't egzumers firmware repo though

I think the reason he keeps raising issues here is Egzumer has stated on telegraph he just merges  yours and Fagci's FW together and nothing more is thats the case anything unrelated to the spectrum is related to your FW.. And I can confirm the issue.. BUT egzumer  will not be merging the commits for  at least a few hours  yet.   having said that would still be best to start the ssue with his repo first.

**Comment by pawol** [comment]
On the latest 1of commit bug is fixed - I confirm
