### ISSUE TITLE
Still RX/TX compander destroys FM audio

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#103]
Still RX/TX compander destroys FM audio. Previous ticket was closed without a fix

**Comment by pawol** [comment]
No, Both QSs have TX/RX enabled in the same time and audio is destroyed completly

**Comment by OneOfEleven** [comment]
The RX compander is broken. will have to remove it till I can fix it.

**Comment by pawol** [comment]
ok. be back soon

**Comment by pawol** [comment]
on commit 429ac36 still bad effect. even 1750Hz tone is almost muted. Tried in two directions, tx/rx compander mode anabled on each QS.

**Comment by pawol** [comment]
Sorry, probably my fault, looks ut works. Need more tests.

**Comment by pawol** [comment]
Ok confirmed that okay.
