### ISSUE TITLE
Improvement - make tone 1750Hz with timer 2-3s

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#105]
Improvement - make tone 1750Hz with timer 2-3s
At the moment it is necessary to press side button twice to stop the tone.
It will be much easier to trigger 2-3s long tone by one button pressing

**Comment by ea7hjb** [comment]
Better than a timer would be to send the tone WHILE the button is pressed. Then stop the tone when release.

**Comment by pawol** [comment]
quite good idea
