### ISSUE TITLE
icon battery

### ISSUE THREAD

**Issue by Braccato** [OneOfEleven/uv-k5-firmware-custom#106]
Ciao 1of11 sul tuo firmware, l'icone della batteria rimane ferma ? le tacche non scendono?

**Comment by lohtse** [comment]
they work as they should so display battery level..

**Comment by Braccato** [comment]
and strange on my radio they stay still they don't go down

**Comment by OneOfEleven** [comment]
So when the battery percent falls to say 35%, the bars are still full ?

**Comment by Braccato** [comment]
Yes today I reached 56% and they were still all full

**Comment by OneOfEleven** [comment]
I don't think the percentage is quite right, we know that, but the bars will start to fall when the percent reaches down to about 40%.

**Comment by Braccato** [comment]
okok
