### ISSUE TITLE
icon COMPANDER TX RX still not show in screen when is active

### ISSUE THREAD

**Issue by Yag00000** [OneOfEleven/uv-k5-firmware-custom#108]

**Comment by Yag00000** [comment]
icon COMPANDER TX RX still not show in screen when is active

**Comment by lohtse** [comment]
you do know Compander is not working properly yet and is as buggy as hell?

**Comment by Yag00000** [comment]
in 1of11 works fine in TX mode only, not RX

**Comment by lohtse** [comment]
> in 1of11 works fine in TX mode only, not RX

Theres quite a lot of discussion about it on telegram and many  devs suggest not even enabling it   even 1of11 says this

ENABLE_COMPANDER              := 0       this is broken, don't bother with it for now .. compander option (per channel)

**Comment by OneOfEleven** [comment]
I'm currently trying the problem in RX mode, no audio from it for some reason.

But I think the OP is talking about just the on-screen indicator (little 'C' character) that should show when the compander is enabled. I'll have a look and see why that might be.

![Compander_indicator](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/51590168/0b11bd90-f702-46ed-a2e8-eb4d7763dd15)

**Comment by OneOfEleven** [comment]
I can't imagine why the little symbol shows for some but not others.

**Comment by wrcrooks** [comment]
@Yag00000 Is this still an issue on the latest firmware?
