### ISSUE TITLE
BLTTRX menu item's name has typo error

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#112]
BLTTRX menu item has probably typo error. It suggests backlight when TX or RX.
It should be rather BLT RX or BLTRX (backlight when RX only )

**Comment by OneOfEleven** [comment]
No thats right, I changed it to turn the backlight on when a signal is first received and when the PTT is pressed.
I can add more options to it though like, OFF, RX, TX or BOTH

**Comment by pawol** [comment]
New feture works as expected. closed.
