### ISSUE TITLE
Copy channel to vfo does not work in 429ac36

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#115]
Copy channel to vfo does not work in 429ac36.
I have freq+name on display A and B. Long pressing of M does not copy frequency into vfo.

**Comment by INDIAJULIETVICTOR** [comment]
Confirm..

https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/145300322/775c81e2-b7de-4a1d-8b5c-fd01ed6075ff

**Comment by OneOfEleven** [comment]
I've just changed how it works. It now takes the current channel, sets the VFO to frequency mode and copies the channel into it (doesn't effect the other VFO).

Have a play

**Comment by INDIAJULIETVICTOR** [comment]
not again..

https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/145300322/61890672-b4bf-41de-a093-f84b7d8eee14

**Comment by INDIAJULIETVICTOR** [comment]
I found...the DUAL WATCH OPTION

`
				if (gEeprom.VFO_OPEN &&
				    // gEeprom.DUAL_WATCH == DUAL_WATCH_OFF &&
				    gScanState == SCAN_OFF &&
				    gCssScanMode == CSS_SCAN_MODE_OFF)
				{	// copy channel to VFO


`
