### ISSUE TITLE
Idea: Another scanlist

### ISSUE THREAD

**Issue by DE8MSH** [OneOfEleven/uv-k5-firmware-custom#116]
Hi 1O11.

Sometimes there's a need to use three (more?) scanlists. Is it possbile to add code/EEPROM space for another scanlist?

**Comment by INDIAJULIETVICTOR** [comment]
I can suggest using the third option : no scan list.. 
in order to scan the other memories without options when the SCAN LIST item is OFF..

**Comment by OneOfEleven** [comment]
> I can suggest using the third option : no scan list.. in order to scan the other memories without options when the SCAN LIST item is OFF..

I've added an 'ALL' option to the scanlist - all channels get scanned
