### ISSUE TITLE
The battery icon shows an extra pixel while charging with USB

### ISSUE THREAD

**Issue by zhaoparrot** [OneOfEleven/uv-k5-firmware-custom#12]
![IMG_20230919_094915](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/27049669/783dea46-cba3-4f90-abaf-11233f40d96e)
is this a bug ?

**Comment by OneOfEleven** [comment]
mmm looks like it, it doesn't happen for me, I have two radios here.

I'll let you know when I find it !

**Comment by M7OCM** [comment]
Great work 111!

Confirm this artifact also appears when the battery charge drops (or is transitioning) from 3 bars to 2. Same on both K5's - latest compilation.

**Comment by OneOfEleven** [comment]
Try it now, I've just uploaded a fix - hopefully.

Let me know if it still shows up.

**Comment by M7OCM** [comment]
Perfect thank you
