### ISSUE TITLE
fast list scanning hardly stop when carrier transmitted on commit 609df5f

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#121]
fast option enabled
fast list scanning does not stop or make it hardly when carrier transmitted on commit 609df5f

Reproduction. 
on 1st QS fast scan list of PMR1 - PMR8 channels triggered
on 2nd QS trigger the PTT
on 1st QS scanning does not stop or make it hardly

**Comment by OneOfEleven** [comment]
I'll remove the fast scan then for now, it was only experimental, need to find the best BK chip settings to do it.
Don't want the headache of dealing with that at the moment.

**Comment by pawol** [comment]
bad news. On standars list scanning speed there is also the issue
