### ISSUE TITLE
standard speed list scanning does not stop or make it hardly when carrier transmitted on commit b343993

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#122]
standard speed list scanning does not stop or make it hardly when carrier transmitted on commit b343993

Reproduction.
on 1st QS fast scan list of PMR1 - PMR8 channels triggered
on 2nd QS trigger the carrier on PMR1 by PTT button or side button (the tone 1750Hz)
on 1st QS scanning does not stop or make it hardly

**Comment by pawol** [comment]
The last known commit with feature working was e042b21

**Comment by pawol** [comment]
On commit 5c346c8 still does not work

**Comment by pawol** [comment]
Tried on 5397b3e with fast scanning - still the same

**Comment by OneOfEleven** [comment]
mmm I'm still tweaking the squelch setting as I go and learn how the RF works and responds,
Still actually learning the code, still parts I've yet to actually see and understand exactly what each and every bit is doing, a big job.

**Comment by pawol** [comment]
Seems to work when fast scanning compiled on commit e042b21

**Comment by wrcrooks** [comment]
> not having a schematic of the radio

https://github.com/ludwich66/Quansheng_UV-K5_Wiki/wiki/Schematics is probably the best that we have (that I've found, at least)
