### ISSUE TITLE
Spectrum 

### ISSUE THREAD

**Issue by rai4424** [OneOfEleven/uv-k5-firmware-custom#127]
Plz add spectrum analyzer.

**Comment by lohtse** [comment]
> Plz add spectrum analyzer.

use egzummers for now.. he has added it already

his FW is 1of11 + Fagcis spectrum

**Comment by LZ2DMV** [comment]
Hi @OneOfEleven,

I saw you integrated spectrum.c from fagci's repo (you probably have plans to work on it later?). Just to let you know that fagci merged his 'refactor' branch into 'main', so his 'main' branch now contains an updated version that is many commits ahead of the one you integrated.

If you plan to work on the spectrum, i think it is best to start from that point. Just an advice, of course.
