### ISSUE TITLE
DTMF issue

### ISSUE THREAD

**Issue by Romashca** [OneOfEleven/uv-k5-firmware-custom#128]
https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/83151488/1429185a-f94f-4e66-bc4b-e7e655f57d3b

**Comment by Romashca** [comment]
https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/83151488/588e7e24-65be-41b3-8575-0dfd690e583b

**Comment by Romashca** [comment]
the problem with dtmf, when pressing ptt 1 and # transmits the same tone as befwhen typing dmf and pressing ptt, nothing happensore pressing #

**Comment by lohtse** [comment]
> the problem with dtmf, when pressing ptt 1 and # transmits the same tone as befwhen , when typing dmf and pressing ptt, nothing happens

could this be related/linked too your other issue???   I don't use dtmf.  and don't have the other issue. hmmmmmmmmmmmmmm

**Comment by Romashca** [comment]
perhaps they are somehow connected? I need a dm to control the repeater

**Comment by Romashca** [comment]
there are no such problems in the repo from 20231005

**Comment by OneOfEleven** [comment]
Yes I broke the keypad stuff yesterday when I made a change, been on the case since tracking a couple of uncovered problems with the keypad code.

**Comment by Romashca** [comment]
I really hope that you will succeed. We will be very grateful to you

**Comment by OneOfEleven** [comment]
Still have a bug in the DTMF entry before TX.

If I enter some DTMF keys in, then stop and let the entry time out (go off screen), the next button press is ignored - that's a bug I MUST find.

**Comment by Romashca** [comment]
you are my hero
