### ISSUE TITLE
Alarm TX issue

### ISSUE THREAD

**Issue by ea7hjb** [OneOfEleven/uv-k5-firmware-custom#130]
Hello,

When compiling with option "ENABLE_ALARM" to have the siren option available, if "AL-MOD" is set to "TONE", it will do TX of the alarm no matter what frequency it is (50MHz, airband... everywhere you are tuned)

Understandably when set to "SITE" alarm should always work, but when set to "TONE", the alarm should play the local sound and refuse to TX if outside the allowed bands (136-600?)

Best regards.

**Comment by OneOfEleven** [comment]
I've removed the bit of alarm code that was bypassing the TX out of band check. I'll upload the fix soon.

In between chilling watching movies (having a relaxing day) I'm slowly searching for a bug I added yesterday, it's to do with entering a DTMF code to transmit (started by pressing the '*' key).

**Comment by Romashca** [comment]
I really hope that you will succeed . We are really looking forward to the update.

**Comment by OneOfEleven** [comment]
I'll find, no worry, I never stop looking for a problem once I know it's there.
