### ISSUE TITLE
REVERSE_BAT_SYMBOL 0  Bug

### ISSUE THREAD

**Issue by Aquila161** [OneOfEleven/uv-k5-firmware-custom#132]
I modified the makefile by setting the :REVERSE_BAT_SYMBOL modification to 0
and I have to report 2 bugs.
![20231006_215403](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/147185371/7469d5b8-ba32-44c9-bb3e-86ff2dc0f480)

**Comment by OneOfEleven** [comment]
I think thats' fixed now. Thank you for letting me know
