### ISSUE TITLE
Battery bars have nothing common with calibration steps made by amnemonic stript

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#136]
Battery bar has nothing common with calibration steps made by amnemonic stript

Here is my battery calibration:
Level 0: [1341] 5.20 V // Empty battery blinking
Level 1: [1805] 7.00 V // 1 battery bar if above this value
Level 2: [1921] 7.45 V // 2 battery bars if above this value
Level 3: [1960] 7.60 V // 3 battery bars if above this value, also value used to calculate adc to volt
Level 4: [2032] 7.88 V // 4 battery bars if above this value
Level 5: [2300] 8.92 V // overwritten by radio to 2300 anyway

Measured battery voltage is right and consistent with real battery's voltage.
Even when voltage on screen is 7.35V still, displayed battery's bars  are full. 
It should show 1-2 bars at most.

**Comment by egzumer** [comment]
This is the same as #139

**Comment by pawol** [comment]
Seems works ok on commit 6660d00

**Comment by OneOfEleven** [comment]
ah good , egzumer fixed that :)
