### ISSUE TITLE
Battery bars not work properly

### ISSUE THREAD

**Issue by LCiccio** [OneOfEleven/uv-k5-firmware-custom#139]
Hello,
in the last commit the battery bars bitmap sign always 100% of battery (with 4 of 4 bars) with every battery voltage.

Thanks in advance for your effort and for your time.

**Comment by Romashca** [comment]
that's right, the battery indicator does not show correctly

**Comment by Romashca** [comment]
the battery ran out , but it showed 3 stripes until the last one . then he blinked and turned off, what does calibration have to do with it?
