### ISSUE TITLE
[Proposal] add channel names to SLIST1 and 2 too

### ISSUE THREAD

**Issue by ANTodorov** [OneOfEleven/uv-k5-firmware-custom#14]
Hello.

First thank you for the great work!

I am wondering is it possible to add the channel names to SLIST1 and SLIST2 too. Currently only the channel number and the optional priority is displayed.  Also, for better user experience maybe the channel name should be placed above the channel number at all menus (channel Delete, SLIST1 SLIST2, etc.).

Best Regards,
Anton

p.s. sorry for the empty issue - my finger slipped to the enter accidentaly :/

**Comment by OneOfEleven** [comment]
You're welcome, though @DualTachyon is the one to thank, I'm just adding to it :)

I've added the channel names to the SLIST menus, I've left the channel number above the name - for now, just looking at something else at the mo.

**Comment by ANTodorov** [comment]
Thank you for the quick response!

Definitely kudos to @DualTachyon! Without hi's talent and hard hard work all of this couldn't be possible!

Just flashed and tested - With the channel number(CH-xxx) on top is looks/feels even better.

Cheers!
