### ISSUE TITLE
No microphone audio transmitted between Quindar tones

### ISSUE THREAD

**Issue by wrcrooks** [OneOfEleven/uv-k5-firmware-custom#141]
Tested Quindar PTT menu option and noticed two things:
- ROGER Beep still needs to be disabled, otherwise the trailing roger beep still gets played after the ending Quindar tone
- No microphone audio gets transmitted between the two tones

I had this problem too when originally writing the Quindar tone code. My workaround to get audio coming through again was to run the "RADIO_SetTxParameters()" method right after calling the "PlaySingleTone(2525Mhz, 250ms)" method. Calling this method seemed to reset the BK4819's registers to take microphone audio properly again.

**Comment by OneOfEleven** [comment]
Serves me right for not testing it properly ;)  I've fixed that now.

A less drastic way to mute/unmute the TX speech audio is to use ..

BK4819_EnterTxMute() and BK4819_ExitTxMute()

I've put a BK4819_ExitTxMute() call at the end of the BK4819_PlaySingleTone() function so as to re-enable TX speech audio.
