### ISSUE TITLE
F+4 problem

### ISSUE THREAD

**Issue by PieeerB** [OneOfEleven/uv-k5-firmware-custom#152]
F+4 cannot detect PMR channels. And not only, for example 433.310 frequency capture also cannot determine

**Comment by OneOfEleven** [comment]
I changed it to round to the nearest current step size. I've added an option to disable that rounding (revert back to how it was).

Set the compile option "**ENABLE_FREQ_CODE_ROUNDING**" in Makefile to '**0**', then recompile.

**Comment by PieeerB** [comment]
now it works perfectly! Thank you very much. The firmware is great
