### ISSUE TITLE
Strangely low background noise above commit e11c0c8

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#157]
The commit e11c0c8 is the latest one when background noise of a  receiver seems to be natural. 
Above that commit a noise is strangely silent and attenuated.
Tested on AM Airband

**Comment by pawol** [comment]
On commit 5755a92 a background noise is back :)

**Comment by OneOfEleven** [comment]
I'd need a video of that to be honest. Noise can be coming from lots of places.

Knowing the structure of the noise would help.
