### ISSUE TITLE
Hidden F-lock menu does not... lock

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#159]
Hidden F-lock menu does not proper frequencies.
For example: CE allows to set any frequency as 446MHz. It shoud be locked there for 430-440 MHz. I am talking about UHF in this case. It worked in the original FW

**Comment by OneOfEleven** [comment]
Well, I've set mine to CE mode, can't get them to TX outside of the 430 to 440 range. Not sure what's causing that problem, I need to reproduce it but can't seem too.

**Comment by pawol** [comment]
I'll try on the latest commit

**Comment by pawol** [comment]
This feature does not lock rx/tx but tx only.
My fault, works on commit 5755a92.
