### ISSUE TITLE
Mic Audio Bar is not working

### ISSUE THREAD

**Issue by JakeWolfie** [OneOfEleven/uv-k5-firmware-custom#160]
Just compiled Yours newest build, flashed it and now I have stuck Mic audio bar when transmitting. It always shows 299 and full scale.

**Comment by OneOfEleven** [comment]
Do you have "**ENABLE_SHOW_TX_TIMEOUT**" set to '1' in Makefile ?

If so, then you're not seeing the mic audio bar, but instead a TX timeout bar (will slowly reduce until your TX times out).

**Comment by JakeWolfie** [comment]
I though TX Timeout is only displayed on the left side as a numbers counting down, disabled TX TO now, everything works great. Sorry for bothering Youm keep up the good work OneOfEleven. That's my fav firmware since I bought K6. Best regards, Jake
