### ISSUE TITLE
wide FM (standard radio service) cannot be received/demodulated by communication receiver

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#167]
wide FM (standard radio service) cannot be received/demodulated by communication receiver.

This issue is known since the beginning of QS. 
For instance when we set to 104,90MHz (local stereo wide FM radio service in my area) then we are not able to hear it clearly.
Demodulation is awfull. 
The question is why. Wide band, signal strenght and FM demodulation should be enough to hear it but it is not.
In the same place I am able to hear that station perfectly by means of RTL-SDR or build in QS separate radio service receiver.

**Comment by OneOfEleven** [comment]
Not sure what you're asking ?

FM broadcast deviation is like 50kHz, narrow band comms deviation is 5kHz or less.

**Comment by pawol** [comment]
Aaa... ok. If standard radio service has 50kHz of deviation then it makes sense on 25kHz wide band of communication chanel

**Comment by OneOfEleven** [comment]
If you want to listen to FM broadcast station, you need to use the wide band FM radio.

**Comment by pawol** [comment]
ok, issue cleared

**Comment by OneOfEleven** [comment]
Some countries have already stopped using the VHF FM broadcast band for broadcast radio, it's now used for others things.
