### ISSUE TITLE
SQUELCH TAIL NOSE

### ISSUE THREAD

**Issue by rai4424** [OneOfEleven/uv-k5-firmware-custom#169]
Noticing squelch tail noise after installing custom FW.
Before, was not present in K5 to K5 and baofeng to K5. Thanks in advance.

**Comment by wrcrooks** [comment]
What are your settings for the following?
- ROGER
- PTT ID
- STE

**Comment by rai4424** [comment]
> What are your settings for the following?
> 
> * ROGER
> * PTT ID 
> * STE.  

ROGER Off
 PTT ID  Off
 STE   On
I have checked with 03 talkies(k5+k5+Baofeng A58) with this setting now. Problem is partially solved.  When K5 with custom Fw Txing, other two make SQ tail noise.

I will be thankful if u clarify for me its funtion.
( I want to close this this issue soon to avoid disterbence for respectful programer)
Thanks

**Comment by OneOfEleven** [comment]
Squelch tail noise is normal for FM, actually unusual not to hear it.

The only way to mute it is to use say CTCSS or CDCSS which has the option to TX a mute tone/code at the end of your TX in order to tell the RX'ing radio to mute its audio early, and so muting the normal FM squelch tail.

I think that's what you're referring to ? .. not long woke up.

**Comment by OneOfEleven** [comment]
STE is the option that tells your TX to send the CTCSS/CDCSS mute tone/code (but only if you're using CTCSS/CDCSS).

**Comment by OneOfEleven** [comment]
ROGER and PTT ID are for different uses, mainly to annoy radio hams.

**Comment by OneOfEleven** [comment]
CTCSS/CDCSS happens in the background at the same time as everything else, you don't hear it as it's normally filtered out in the RX'ing radio before it reaches the speaker.

It's like when elephants and whales talk to each other, they use LF audio that hour hears don't respond to.

**Comment by rai4424** [comment]
Thanks

**Comment by rai4424** [comment]
Thanks
