### ISSUE TITLE
Menu 20: No EXIT at OFF

### ISSUE THREAD

**Issue by DE8MSH** [OneOfEleven/uv-k5-firmware-custom#17]
Hi 1O11.

if I set BACKL to OFF and want to exit it won't let me exiting. But I like to exit again ;) Values above OFF working.

**Comment by OneOfEleven** [comment]
Couldn't find my way back to the backlight menu option after turning it off on mine lol.

Anyway, hopefully fixed. Let me knoiw.

**Comment by DE8MSH** [comment]
Use a flashlight to get back. LOL. Tnx. I'll try...

**Comment by DE8MSH** [comment]
Hello 1O11. Works like a charm again. :)

**Comment by DE8MSH** [comment]
Sorry. I've to reopening it. EXIT on light OFF doesn't work.

**Comment by DE8MSH** [comment]
Did you do a re-do commit here? A few 10 minutes ago it worked?!

**Comment by OneOfEleven** [comment]
It seems only to do it under certain sequences, looking for the bug now.

**Comment by OneOfEleven** [comment]
Right, I found it this time.

Plus I've made the backlight come on when you go the backlight menu no matter what it's set to - so the user can see what they are doing (I couldn't see any text due to low light level in the room)  !

**Comment by DE8MSH** [comment]
Now it stays on >=10 seconds at OFF.

**Comment by DE8MSH** [comment]
...until I reach BLIGHT menu??? hahahaha then its turning on?!

**Comment by OneOfEleven** [comment]
Only while your setting/changing the menu option, once the light goes off it won't come back on, until you visit the backlight menu again.

I've done that because the screen can't be seen in low light conditions, so finding the backlight menu is possible if the light comes on for that 10 seconds when you cross the backlight menu.

**Comment by DE8MSH** [comment]
Got it. It's more intelligent Light management if light stays on whole time at menu? and if you quit it: turn light off immediately if menu quitting with exit button? ( in later version) ;)

**Comment by DE8MSH** [comment]
but: no exit at LIGHT OFF is closed now.
