### ISSUE TITLE
Feature Request: Side Button for Secondary PTT

### ISSUE THREAD

**Issue by cloudwindy** [OneOfEleven/uv-k5-firmware-custom#177]
Switching between A and B channels is a bit of inconvenience, is it possible to customise the side button to PTT on the secondary channel?

**Comment by cloudwindy** [comment]
Sorry! Dup #84.

**Comment by OneOfEleven** [comment]
All you do is press and hold 2/A/B button to toggle between the VFO's. Not sure how using a side button would make it any easier ?
