### ISSUE TITLE
There is a bug that when I flash the firmware with version number 14105a4, I can't use Fn+2 in radio mode.

### ISSUE THREAD

**Issue by acjzdpbb** [OneOfEleven/uv-k5-firmware-custom#179]
There is a bug that when I flash the firmware with version number 14105a4, I can't use Fn+2 in radio mode.

**Comment by acjzdpbb** [comment]
After flashing the firmware version 14105a4, the scanning function in radio mode is gone

**Comment by OneOfEleven** [comment]
Well don't use 14105a4 ?
