### ISSUE TITLE
Another vfo display issue

### ISSUE THREAD

**Issue by zhaoparrot** [OneOfEleven/uv-k5-firmware-custom#18]
in vfo mode . I type in 438.500 00 and set step to 12.5k
then i press up key 
i was expecting 438.512 **50** but I got a 438.512 **00**
I have BIG_FREQ enabled

**Comment by OneOfEleven** [comment]
Have fixed that, sorry.

I'll upload the fixed code shortly, just trying to find the battery menu exit bug.

**Comment by M7OCM** [comment]
Thanks 111
