### ISSUE TITLE
Broken AM fix

### ISSUE THREAD

**Issue by subsubl** [OneOfEleven/uv-k5-firmware-custom#191]
Was this a revert, AM fix just went back to the first atempt version, hiss and low volume over noise, no problem a few days ago.

**Comment by subsubl** [comment]
Normal operation of AM on fagci and 1of11 versions from a few days ago.

**Comment by OneOfEleven** [comment]
> Was this a revert, AM fix just went back to the first atempt version, hiss and low volume over noise, no problem a few days ago.

Yes I've reverted it to back to when I first started to code the fix.

**Comment by subsubl** [comment]
Will do it later, on the move atm. 30min.. :) So the fix kinda hisses and drowns the volume of the AM modulation, some random oscillation also heard wizzing tru.
