### ISSUE TITLE
Thank you for your modification. SBAR displays suggestions for modification

### ISSUE THREAD

**Issue by SylarMa** [OneOfEleven/uv-k5-firmware-custom#192]
Thank you for your modification. 

SBAR displays suggestions for modification.

The current mic-bar and s-bar display bars are not clear and cannot accurately indicate the numerical situation

Can you use the style of @piotr022

![rssi_sbar](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/34432937/ea355c00-a175-4382-abd7-85bb197655a6)

**Comment by xDraker** [comment]
Exist the possibility in the menu of Tx BAR to add enable and disable the TX Timeout?

**Comment by OneOfEleven** [comment]
I like it as it is
