### ISSUE TITLE
Suggestion: Extend FM Radio Frecuency Range 64-108 MhZ

### ISSUE THREAD

**Issue by xDraker** [OneOfEleven/uv-k5-firmware-custom#193]
Can be possible to extend the WBFM VHF broadcast band receiver frecuency range to 64-108 MhZ?

Thank You

**Comment by OneOfEleven** [comment]
I've done that, easy enough. Added a compile option in Makefile

**Comment by OneOfEleven** [comment]
Well, not 64MHz but 68MHz
