### ISSUE TITLE
Date and time moved to the right

### ISSUE THREAD

**Issue by Aquila161** [OneOfEleven/uv-k5-firmware-custom#199]
Hi, I didn't touch anything, I just compiled the firmware with the date written and moved to the right, how can I solve it?
Thank you
![20231020_174006](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/147185371/ff3346b5-9288-47f7-8ab7-678faf3958f9)

**Comment by OneOfEleven** [comment]
no idea
