### ISSUE TITLE
ENABLE_BOOT_BEEPS := 0 == Error

### ISSUE THREAD

**Issue by DE8MSH** [OneOfEleven/uv-k5-firmware-custom#2]
Hello. 

If we set 

`ENABLE_BOOT_BEEPS             := 0`

this message shows up:

`app/app.c: In function 'APP_CheckKeys':
app/app.c:1189:4: error: 'boot_counter_10ms' undeclared (first use in this function)
 1189 |    boot_counter_10ms   = 0;
      |    ^~~~~~~~~~~~~~~~~
app/app.c:1189:4: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:240: app/app.o] Fehler 1
`

**Comment by OneOfEleven** [comment]
Sorry about that, I've fixed it now - hopefully.

Feel free to let me know if any more problems.

**Comment by DE8MSH** [comment]
Worx 100%.
