### ISSUE TITLE
small bold font

### ISSUE THREAD

**Issue by IU4FIR** [OneOfEleven/uv-k5-firmware-custom#207]
Maybe I'm missing something, but is there an option to use the bold character for the channel name, without using the compiler?
73?
![Immagine 2023-10-22 170047](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/96939950/5e16b839-7bf3-4b69-a8f0-a96f921379cd)
![new firmware](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/96939950/015fd979-ed22-4763-9299-500c5288818b)

**Comment by OneOfEleven** [comment]
no

The reason for the compiler options is to remove code from the firmware. So disabling the bold font frees up flash bytes needed by something else.

You need to compile with yourself with your desired compiler options.

**Comment by IU4FIR** [comment]
Ok, but the only way to modify the fw is by using the method indicated in your README.md file; it is not possible to use "VISUAL CODE" or other native Windows software?
