### ISSUE TITLE
VHF Band II

### ISSUE THREAD

**Issue by pdrbsts** [OneOfEleven/uv-k5-firmware-custom#208]
Please change the FM broadcast lower frequency from 88 to 87.5 MHz.
https://en.wikipedia.org/wiki/Band_II

**Comment by ea7hjb** [comment]
FM should be from 76 to 108, as some countries begin in 76 (Japan, 76-95, Brazil 76-108). So leaving 76-108 you are sure to always be right. It could be programmable, but I'm not sure it we should ask OneOfEleven to do that job. Having it wide open and letting the user use his/her brain should be the recommended choice.

**Comment by OneOfEleven** [comment]
I can add a hidden menu option so the user can set the FM radio limits.

**Comment by ea7hjb** [comment]
> I can add a hidden menu option so the user can set the FM radio lower limit being as it varies around the world.
> 
> The chip can do 68 to 108, but I doubt the RF front end filter covers the full range, but don't know without checking it on the signal generator.

It is not up to me do decide but, running so low of space, as you are well aware, is that necessary? If you want to make it programmble, would it not be better (in terms of space) to decide that during compile time in the Makefile?

**Comment by OneOfEleven** [comment]
Either really.

I'll go the compile option route then, you're right, it won't use any extra flash bytes.
