### ISSUE TITLE
Change upper airband limit from 136 to 137 MHz

### ISSUE THREAD

**Issue by pdrbsts** [OneOfEleven/uv-k5-firmware-custom#209]
Change upper airband limit from 136 to 137 MHz.
This has changed on Jan 1st 1990.
https://www.faa.gov/documentLibrary/media/Advisory_Circular/AC90-50D.pdf

**Comment by ea7hjb** [comment]
Indeed it should be from 108 to 137.

**Comment by pdrbsts** [comment]
You fixed it! Awesome! Thank you.

**Comment by OneOfEleven** [comment]
While I was tested it last night I noticed a bug when manually moving up/dn in frequency (using the up/dn buttons), the did something strange when rolling over between 137back down to 108 or visa versa.

I'll find the bug and fix.

**Comment by OneOfEleven** [comment]
fixed
