### ISSUE TITLE
SCAN RESUME TIME

### ISSUE THREAD

**Issue by PieeerB** [OneOfEleven/uv-k5-firmware-custom#210]
SCAN RESUME TIME -This parameter does not work correctly, the radio station waits for the end of the transmission and continues scanning

**Comment by OneOfEleven** [comment]
Hopefully fixed, let me know of any problems at all.

In the early days I didn't understand much of the code layout and what all the variables did etc, so basically now fixing any bugs I may have introduced back then ;)
