### ISSUE TITLE
ENABLE_SMALL_BOLD 

### ISSUE THREAD

**Issue by IT9-TOP** [OneOfEleven/uv-k5-firmware-custom#222]
Hi, some information, if I select the ENABLE_SMALL_BOLD 1 function, the firmware doesn't compile, it gives me an error, how can I solve it?

**Comment by wrcrooks** [comment]
What's the compilation error? Can you paste it in here please?

**Comment by IT9-TOP** [comment]
![wer](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/148902977/30b72d84-2a93-4728-8007-a592d80cd45e)

**Comment by wrcrooks** [comment]
The resolution would be to set other makefile options to 0 (disabled) so your compiled firmware is small enough to fit in the NVRAM on the radio. The compiler is telling you that with everything enabled that you have enabled, the binary would not fit on the radio.

**Comment by IT9-TOP** [comment]
I only activated ENABLE_SMALL_BOLD 1

**Comment by OneOfEleven** [comment]
You're running out of flash space, you'll have to disable something else to use bold fonts.

Might be enough to disable the debug code I use by setting this (none of you need that) ..

ENABLE_UART_DEBUG  := 0

**Comment by OneOfEleven** [comment]
is it OK now ?

**Comment by SylarMa** [comment]
make (e=2): The system could not find the specified file.
make: *** [clean] Error 2

make: [all] Error 9009 (ignored)

**Comment by OneOfEleven** [comment]
ignore that.

So long as you get the firmware.packed.bin file back that's all that matters.

**Comment by SylarMa** [comment]
i get it

Can the MDC1200 encode and decode?

**Comment by OneOfEleven** [comment]
yes, but that's for the thread

**Comment by SylarMa** [comment]
It would be nice if the MDC1200 could be emitted with DTMF ID
