### ISSUE TITLE
VFO "remembers" old TX frequency

### ISSUE THREAD

**Issue by Mason10198** [OneOfEleven/uv-k5-firmware-custom#226]
I noticed that when keying in a new frequency in VFO mode, the TX will go to the last frequency used (before the VFO was changed) when the PTT is pressed as if it were a TX offset, but no TX offset is enabled. Turning the power off/on each time after changing frequency in VFO fixes this.

**Comment by OneOfEleven** [comment]
oops, thought I'd fixed that, I'll get to it !

**Comment by OneOfEleven** [comment]
Should be OK now, sorry about that.
