### ISSUE TITLE
Compnd's C flag is offset off the screen

### ISSUE THREAD

**Issue by SylarMa** [OneOfEleven/uv-k5-firmware-custom#229]
Compnd's C flag is offset off the screen

In ch-dis, the frequency name will overflow off-screen when it is 10 characters

**Comment by OneOfEleven** [comment]
need a picture showing that

**Comment by SylarMa** [comment]
![IMG_20231025_190900](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/34432937/7c6998d0-f52f-4b7e-bf74-8fb2c005432c)
![IMG_20231025_190845](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/34432937/00f31def-2106-4456-8a8e-ffdc2f4e2870)

**Comment by OneOfEleven** [comment]
actually the 'C' is fine, that is the what the C looks like in the smallest font.

**Comment by SylarMa** [comment]
if the hrb-650~sb becomes shorter,then the STE display will be fine.

**Comment by SylarMa** [comment]
The display is already normal, but the c display is not good looking

**Comment by OneOfEleven** [comment]
no ?

Looks like a little 'C' to me, they are tiny characters, 3 pixels wide by 5 pixels in height..

**Comment by SylarMa** [comment]
ok That looks very cool
