### ISSUE TITLE
No H/M/L if QRG is on 'TX DISABLED'

### ISSUE THREAD

**Issue by DE8MSH** [OneOfEleven/uv-k5-firmware-custom#23]
Hi 1O11.

If freq is on 'TX DISABLED' it makes no sense to show L/M/H on display.
can we disable it?

**Comment by OneOfEleven** [comment]
Yes sure no problem.

I'm just chilling at mo, having a first look at telegram, but i'm not a social media fan, just youtube. Anyway, bare with me, dosed out on painkillers ;)

**Comment by DE8MSH** [comment]
i just saw 👋🏻👋🏻👋🏻👋🏻👋🏻

**Comment by OneOfEleven** [comment]
:)
