### ISSUE TITLE
Trim Trailing Zeros

### ISSUE THREAD

**Issue by wrcrooks** [OneOfEleven/uv-k5-firmware-custom#230]
I believe that the Makefile logic has the inverse effect on the behavior of the radio. When `ENABLE_TRIM_TRAILING_ZEROS := 0` the trailing zeros are trimmed and when `ENABLE_TRIM_TRAILING_ZEROS := 1` the trailing zeros are visible.

**Comment by OneOfEleven** [comment]
That can't be ??

**Comment by OneOfEleven** [comment]
It's set to '1' for me, the trailing zeros are gone.

**Comment by OneOfEleven** [comment]
Post an image if you can.

**Comment by wrcrooks** [comment]
Interestingly, I've just compiled it with the option enabled and disabled and the VFO shows the trailing zeros either way.

With it set to '1'
![image](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/84979284/ee10c881-1d36-44a6-ad41-5da90a94f49f)
![20231025_155051](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/84979284/10ec7e00-2ec2-43a3-8801-a4a1a1aeddad)

With it set to '0'
![image](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/84979284/1c243033-0e83-453a-9347-fdafba43d27e)
![20231025_155529](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/84979284/472923bb-3acf-42bf-a374-cfb91aeae50e)

**Comment by OneOfEleven** [comment]
ah, i see !

I haven't yet got to removing the trailing zeros from the bug frequency read outs, done the smaller mode ones though.

**Comment by OneOfEleven** [comment]
You use big font mode, I should really do that myself on and off to test things out, but never do.

**Comment by wrcrooks** [comment]
And now that you say that, I see too :smiley: I noticed the trailing zeros were gone when I merged your changes (including having the BIG_FREQ disabled).

As for testing with big font mode, it's your firmware for your end user experience, you shouldn't have to! Haha

**Comment by wrcrooks** [comment]
Just a question based on your experience with the code, does this feature operate such that it doesn't paint the trailing zeros on the UI (thus saving code space) or that it has additional logic to remove the trailing zeros from the UI (thus taking up more FLASH storage)?

**Comment by OneOfEleven** [comment]
Try it now with big font

**Comment by OneOfEleven** [comment]
It does take a bit more to remove trailing zeros, I have to check each trailing char until I reach a non-zero (going backwards).

**Comment by wrcrooks** [comment]
Tested the changes and it works with big font, up to one digit after the decimal (440.000 changes to 440.0)

Thanks for the fix!

**Comment by OneOfEleven** [comment]
I could remove the last zero and decimal point but I prefer to keep them

**Comment by wrcrooks** [comment]
No objections here, I like it too. 

In my testing this option takes up 44 bytes, in case you want to put that in the README
