### ISSUE TITLE
Roger > MDC original

### ISSUE THREAD

**Issue by IT9-TOP** [OneOfEleven/uv-k5-firmware-custom#233]
hi, I don't like the implemented MDC 1200 function, I would like to restore the original MDC sound, what modification should I make?
Thank you so much for the work you do.

**Comment by zhaoparrot** [comment]
OneOfEleven starts to code with MDC stuff about 3days ago,[ here ](https://github.com/OneOfEleven/uv-k5-firmware-custom/activity)you can track down the detail of what he did and reverse it in you code.

**Comment by OneOfEleven** [comment]
MDC is not a cb'ers roger bleep, it's a way of transferring a tiny bit of data during transmission, why the chinese think it's a roger is a bit confusing.
