### ISSUE TITLE
After great MDC1k2 success: Is this possible, too?

### ISSUE THREAD

**Issue by DE8MSH** [OneOfEleven/uv-k5-firmware-custom#236]
POCSAG:

https://habr.com/en/articles/438906/
https://www.afundr.de/funkruf/65-pocsag
https://www.qsl.net/kb9mwr/projects/pager/plan.html

It's possible to enter a small txt and TX it maybe? But 1st test can be a friendly "Hello World".

I have a Pager -- on Ham Radio QRG -- and I can test 👋🏻😬

But I don't know if K5 can transmit this -4,5/+4,5 kHz.

**Comment by OneOfEleven** [comment]
The K5 can do direct FM (aircopy is direct FM), POCSAG is direct FM, but I think there are 2 level and 4 level version of it, not sure. The K5 can't do 4-level FM, only 2-level, or at least we only know how to configure the chip to do 2-level FM.

Anyway, I'm still working on mdc1200 to find out the exact reason for some moto radios seemingly not reacting as expected to the packets.

POCSAG will be someone elses dev branch.

**Comment by DE8MSH** [comment]
Yes. Fully agree. 👍🏻
