### ISSUE TITLE
the nearby radio will receive a brief signal prompt.

### ISSUE THREAD

**Issue by SylarMa** [OneOfEleven/uv-k5-firmware-custom#247]
When you press the menu button, up and down buttons, etc., the nearby radio will receive a brief signal prompt.

**Comment by wrcrooks** [comment]
Can you post a video of the issue?

**Comment by SylarMa** [comment]
https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/34432937/60f87885-34f3-4ec8-a4d6-6e16b580cf55

**Comment by SylarMa** [comment]
Irregular appearance
I emit at frequency 438.500, and then press M, it will appear. Other operations may also appear, irregular.
 You can try various operations to see.
 I think M, up, down, appears more frequently
