### ISSUE TITLE
Request/Feature idea: AFSK messenger with DTMF activation to receive

### ISSUE THREAD

**Issue by karacsonyisandor** [OneOfEleven/uv-k5-firmware-custom#251]
It would be nice to have text messages on radio without activating manually the AFSK receive function. My idea is to have a specific dtmf sequence sent from the TX radio that would be decoded on RX side. If that specific code is received the RX would switch to AFSK receive and would display the message and switch back to FM. 
Also this way you could send a message to a specific radio based on ANI ID or to a group. 
Thanks.

**Comment by OneOfEleven** [comment]
I'm sure someone will create a fork to do that for you, just not me.
