### ISSUE TITLE
Not work air copi

### ISSUE THREAD

**Issue by IT9-TOP** [OneOfEleven/uv-k5-firmware-custom#252]
Hi, I have to point out that compiling the firmware does not activate the air copy function.

**Comment by DualTachyon** [comment]
You can just edit the makefile and enable it? This is not worth posting a.new issue for?

**Comment by IT9-TOP** [comment]
I enabled air copy on makefile but it doesn't activate. If it didn't work I wouldn't publish the error, I'm not stupid.
