### ISSUE TITLE
Take care yourself 

### ISSUE THREAD

**Issue by Zahurzahur** [OneOfEleven/uv-k5-firmware-custom#262]
Sir
I am new member of  Github and user of K5(8). You are working great for us without any reward  I m noticing that you are working day and nigt and making amendments and corrections in K5 FW. It will effect on your health so please take care of your health because you are our asset.

**Comment by OneOfEleven** [comment]
Yes, you are right. Reason I stay well away from anti social media is because theirs's always someone lurking around that next corner waiting for their next target, but I like peace and quiet these days, I prefer to keep all that rubbish and hassle well away so I can play.
