### ISSUE TITLE
Problem in reception of some stations 

### ISSUE THREAD

**Issue by Zahurzahur** [OneOfEleven/uv-k5-firmware-custom#270]
During reception of a station which was connecting with many other stations. My K5 radio was receving comunitions with cuts even  signals were strong. With monitor on there were no cuts. I m testing again and again. This isue is with few stations. My Kenwood has no any isue like that .  I have tried old FWs but isue was present even  in stock FW. 
Now I m testing on other stations, even on strongest signal the RSS bar is also fluctuating. This is happening with particular stations.

**Comment by OneOfEleven** [comment]
Need to see and hear a short video of it happening, ignore the RSSI bar for now, that's purely cosmetic.

**Comment by rai4424** [comment]
How can I post video?

**Comment by Zahurzahur** [comment]
https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/149041689/792c7448-fa89-4a28-b462-15d6c2de12bf

**Comment by Zahurzahur** [comment]
Above video is with squel on- squelch off- squelch on.

**Comment by OneOfEleven** [comment]
ah, set the channel to **WIDE** mode, the signal looks to be too wide for narrow mode (you have that channel set to **NARROW** mode).

Let me know how it goes.

**Comment by Zahurzahur** [comment]
I m so 😜
