### ISSUE TITLE
"The file version is error"

### ISSUE THREAD

**Issue by tevevizor** [OneOfEleven/uv-k5-firmware-custom#271]
How do I go around the "the file version is error" warning which prevents me from flashing the firmware using the "Portable radio updater"?
I use the UV-K5 (8).

**Comment by DualTachyon** [comment]
You can use this tool instead:

https://github.com/OneOfEleven/k5prog-win

**Comment by tevevizor** [comment]
Thanks, thought k5prog was only for Linux.

**Comment by tevevizor** [comment]
Closed.
