### ISSUE TITLE
TX DISABLE still remain on radio display 

### ISSUE THREAD

**Issue by IU4FIR** [OneOfEleven/uv-k5-firmware-custom#274]
fw b85ea56
radio  receiving on AIR BAND
PRESS PTT > TX DISABLE > it's OK!
TX DISABLE still remain on display, to stop you need to TURN OFF the radio
https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/96939950/d0f38b35-ec8f-4496-b098-8d917a1338a1

**Comment by OneOfEleven** [comment]
Show me with a short little video, I need to see what happens.

**Comment by OneOfEleven** [comment]
Try it now, should be OK.

No need to turn radio off and on again, any display update would have cleaned the message such as channel/frequency change etc. But it's fixed now.

**Comment by IU4FIR** [comment]
Perfect!

**Comment by tevevizor** [comment]
I also noticed it, got rid of the message by pressing "exit" every time. Glad it's solved.
