### ISSUE TITLE
Last frequency digit obscured by something

### ISSUE THREAD

**Issue by krotoniec** [OneOfEleven/uv-k5-firmware-custom#277]
First of all, I hate to see you go. You guys are doing great stuff here, and I have a great time playing with it. Thank you for that either way.
There is an issue with the display in 010ee10. 

![image](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/45798336/900f6251-d9f0-40f0-b13f-f923a7301107)

**Comment by OneOfEleven** [comment]
ah, that's the 3-digit channel number I was playing with yesterday, I'll go back to just an 'F' if it won't fit .

That little number is simply letting you know that its found the frequency you have the VFO set in one of your memory channels, and so is just showing the channel number of the memory it's found it in. Just a bit of info really.

Thank you for letting me know.
