### ISSUE TITLE
cannot compile the latest commit when keylock = 1

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#282]
ENABLE_FASTER_CHANNEL_SCAN -DENABLE_RX_SIGNAL_BAR -DENABLE_TX_AUDIO_BAR -DENABLE_COPY_CHAN_TO_VFO_TO_CHAN -DENABLE_SIDE_BUTT_MENU -DENABLE_KEYLOCK  -I c:/1of11/ -I c:/1of11//external/CMSIS_5/CMSIS/Core/Include/ -I c:/1of11//external/CMSIS_5/Device/ARM/ARMCM0/Include -c app/action.c -o app/action.o
arm-none-eabi-gcc  -Os -Werror -mcpu=cortex-m0 -freorder-blocks-algorithm=stc -std=c11 -MMD -flto=2 -Wall -Wextra -Wpedantic -DPRINTF_INCLUDE_CONFIG_H -DGIT_HASH=\"2638d80\" -DENABLE_FMRADIO_875_108 -DENABLE_FMRADIO -DENABLE_UART -DENABLE_SMALL_BOLD -DENABLE_MUTE_RADIO_FOR_VOICE -DENABLE_VOX -DENABLE_REDUCE_LOW_MID_TX_POWER -DENABLE_TX1750 -DENABLE_KEEP_MEM_NAME -DENABLE_WIDE_RX -DENABLE_F_CAL_MENU -DENABLE_CTCSS_TAIL_PHASE_SHIFT -DENABLE_REVERSE_BAT_SYMBOL -DENABLE_AM_FIX -DENABLE_FASTER_CHANNEL_SCAN -DENABLE_RX_SIGNAL_BAR -DENABLE_TX_AUDIO_BAR -DENABLE_COPY_CHAN_TO_VFO_TO_CHAN -DENABLE_SIDE_BUTT_MENU -DENABLE_KEYLOCK  -I c:/1of11/ -I c:/1of11//external/CMSIS_5/CMSIS/Core/Include/ -I c:/1of11//external/CMSIS_5/Device/ARM/ARMCM0/Include -c app/app.c -o app/app.o
app/app.c: In function 'APP_process_key':
app/app.c:2499:28: error: 'struct <anonymous>' has no member named 'g_eeprom'
 2499 |     g_eeprom.config.setting.g_eeprom.key_lock       = false;
      |                            ^
make: *** [app/app.o] Błąd 1
Press any key to continue . . .

**Comment by OneOfEleven** [comment]
fixed :)
