### ISSUE TITLE
the latest commit cannot be compiled when f_cal=1

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#283]
BUTT_MENU -DENABLE_KEYLOCK  -I c:/1of11/ -I c:/1of11//external/CMSIS_5/CMSIS/Core/Include/ -I c:/1of11//external/CMSIS_5/Device/ARM/ARMCM0/Include -c app/main.c -o app/main.o
arm-none-eabi-gcc  -Os -Werror -mcpu=cortex-m0 -freorder-blocks-algorithm=stc -std=c11 -MMD -flto=2 -Wall -Wextra -Wpedantic -DPRINTF_INCLUDE_CONFIG_H -DGIT_HASH=\"bb3b681\" -DENABLE_FMRADIO_875_108 -DENABLE_FMRADIO -DENABLE_UART -DENABLE_SMALL_BOLD -DENABLE_MUTE_RADIO_FOR_VOICE -DENABLE_VOX -DENABLE_REDUCE_LOW_MID_TX_POWER -DENABLE_TX1750 -DENABLE_KEEP_MEM_NAME -DENABLE_WIDE_RX -DENABLE_F_CAL_MENU -DENABLE_CTCSS_TAIL_PHASE_SHIFT -DENABLE_REVERSE_BAT_SYMBOL -DENABLE_AM_FIX -DENABLE_FASTER_CHANNEL_SCAN -DENABLE_RX_SIGNAL_BAR -DENABLE_TX_AUDIO_BAR -DENABLE_COPY_CHAN_TO_VFO_TO_CHAN -DENABLE_SIDE_BUTT_MENU -DENABLE_KEYLOCK  -I c:/1of11/ -I c:/1of11//external/CMSIS_5/CMSIS/Core/Include/ -I c:/1of11//external/CMSIS_5/Device/ARM/ARMCM0/Include -c app/menu.c -o app/menu.o
app/menu.c: In function 'writeXtalFreqCal':
app/menu.c:64:27: error: 'struct <anonymous>' has no member named 'BK4819_xtal_freq_low'
   64 |    g_eeprom.config.setting.BK4819_xtal_freq_low = value;
      |                           ^
app/menu.c: In function 'MENU_ShowCurrentSetting':
app/menu.c:1335:51: error: 'struct <anonymous>' has no member named 'BK4819_xtal_freq_low'
 1335 |     g_sub_menu_selection = g_eeprom.config.setting.BK4819_xtal_freq_low;
      |                                                   ^
make: *** [app/menu.o] Błąd 1
Press any key to continue . . .

**Comment by pawol** [comment]
Flash size with option as always is exceeded

**Comment by OneOfEleven** [comment]
Yes I'm slowly working on trying to reduce the code size, it's grown too much with the various options added over time.  Going to have to make some sacrifices with the functionality :(
