### ISSUE TITLE
On commit 88f0ee2 side button does not trigger tone 1750Hz

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#285]
On commit 88f0ee2 side button does not trigger tone 1750Hz

**Comment by OneOfEleven** [comment]
It does for me. Have you compiled with the 1750Hz option enabled ?

**Comment by pawol** [comment]
yes, the tone is assigned to the side button

**Comment by pawol** [comment]
On the latest commit 7e5605c the issue is not reproductible

**Comment by OneOfEleven** [comment]
That's cause I simply enabled the 1750Hz tone in the compile options to fix your report. Same applies as per previous user, you each need to pick your desired compile options and compile away for yourselves.
