### ISSUE TITLE
Several issues with 3681674

### ISSUE THREAD

**Issue by krotoniec** [OneOfEleven/uv-k5-firmware-custom#286]
As always, I'm very grateful for you work, however, there are some issues with 3681674.

1. "READING EEPROM" massage upon boot, I don't think it's desired.
2. Channel MODE indicators are gone from the main screen
3. Channel N/W indicator is gone as well
4. Channel SCRAM indicator gone.
5. Channel CTCSS/CDCSS indicators gone
6. Channel Tx PWR indicators gone.

I think there could be a general problem with all channel related indicators.

**Comment by krotoniec** [comment]
Yes, channel details are back, only the EEPROM message is still there.
Thanks!

**Comment by tevevizor** [comment]
> Yes, channel details are back, only the EEPROM message is still there. Thanks!

Can confirm, just checked it.
