### ISSUE TITLE
Frequence offset bug

### ISSUE THREAD

**Issue by chaolucky18** [OneOfEleven/uv-k5-firmware-custom#289]
when you setting the "Tx OFS", input done and then press "menu",it can`t be save.

for example, if now freq is 5.0MHz, set to 8.0MHz, then save, you will find it is back to 5.0MHz.

( firmware git commit info:  7e5605cd18d59f9e0b73233c0940a65ba2704f1c )

-----
btw, thanks for your firmware~ ; )

**Comment by OneOfEleven** [comment]
should be OK now.

Bare in mind that it won't let you set a TX offset value if the frequency/channel is an airband one.
