### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by lohtse** [OneOfEleven/uv-k5-firmware-custom#291]
Just built using latest cmmits

now I get a boot screen with what ever it says(whats the point btw)   then a blank screen with backlight always on.. it is recieving but no ideas  whats going on

also NO FM radio again

**Comment by dutn** [comment]
Same here; black screen during boot.
FM radio only works when Dual Watch is disabled (with firmware from yesterday)

Thank you again for your great work,
Peter.

**Comment by tevevizor** [comment]
For me a3d603e works, except FM radio.
Also, what's the point of the boot screen? Shows up even if ponmsg is disabled.

**Comment by krotoniec** [comment]
> For me [a3d603e](https://github.com/OneOfEleven/uv-k5-firmware-custom/commit/a3d603ea832b3aa79dbdacc1431f8520e90c9426) works, except FM radio. Also, what's the point of the boot screen? Shows up even if ponmsg is disabled.

Indeed it seems a little strange to still have a boot screen when ponmsg is set to none. It's ever weirder in my case since I'm not running it on UV-K5(8) or UV-K6 but on UV-5R ;)

**Comment by OneOfEleven** [comment]
lol, argue amongst yourselves for a while, busy for a while today. I'll take a look at the blank bug later.

**Comment by OneOfEleven** [comment]
Depends if you behave, or not !

**Comment by wrcrooks** [comment]
> At the time of opening this the other was not showing up in the issues list

Everyone is just really quick on the draw, I get it :smile:

**Comment by wrcrooks** [comment]
> Depends if you behave, or not !

Okay okay, I'll behave!! Just please... don't take away my Quansheng! :cry: :laughing:

**Comment by OneOfEleven** [comment]
Well, I now load the entire eeprom contents into memory at boot up, this takes time for the little CPU to do, so while it's busy doing that I stick something (or nothing) onto the screen.

**Comment by OneOfEleven** [comment]
>It's ever weirder in my case since I'm not running it on UV-K5(8) or UV-K6 but on UV-5R ;)

Think of it as an upgrade, old radio made new.

**Comment by krotoniec** [comment]
> > It's ever weirder in my case since I'm not running it on UV-K5(8) or UV-K6 but on UV-5R ;)
> 
> Think of it as an upgrade, old radio made new.

Sure thing, I like it already, just have to remove the old markings and I'm good to go :)

**Comment by mjwgeek** [comment]
> Ran multiple builds to see if I could find the culprit that causes my blank screen.... it happened when contrast menu is enabled!

Confirmed on my end as well.

**Comment by OneOfEleven** [comment]
You found it !

I fixed it !

**Comment by OneOfEleven** [comment]
Applause for finding it, feel free to go pop some balloons ..

https://s1.radiosondy.info

**Comment by reppad** [comment]
Well done to you 2!
Maybe off-topic in this issue but about the debated message, an idea would be to force the display of POnMsg and load the eeprom while it is displayed?

**Comment by OneOfEleven** [comment]
I was thinking about that, I'd need to precede reading the full eeprom contents with first reading just the battery calibration from eeprom, otherwise there would be no battery data to use to display calibrated battery details.

Reducing code size is currently a priority though rather than adding more.

**Comment by OneOfEleven** [comment]
Done the power-on screen.

**Comment by reppad** [comment]
> Well, I now load the entire eeprom contents into memory at boot up

I was wondering what was the advantage of doing this, if you have a few moments for light up my lantern?

**Comment by OneOfEleven** [comment]
Before, the CPU had to continually read the eepom every time it needed any channel details (frequency, name etc) - that takes time and was slowing it all down, particularly when scanning channels.
Now that I have the entire eeprom contents in memory, the CPU has direct and immediate access to all channel, config and calibration data in an instant. no having to go through reading the eeprom each and every time.

The CPU still has to write any changes back to eeprom, ie when the user edits, adds, deletes a channel or menu setting of any kind, but nothing can be done about that.

**Comment by reppad** [comment]
Yes, it makes sense, well seen!
There is enough RAM to store all EEPROM  datas !? Too bad they couldn't be so generous with the size of the flash memory...

**Comment by OneOfEleven** [comment]
Yes, the EEPOM is 8kB in size, the CPU has 16kBs of RAM, so it fits OK.

The CPU has 64kB of flash (top couple of K used by the bootloader though. but, if the CPU's are anything like the STM32 CPU's, it MIGHT actually have 128kB flash, but that's a big MIGHT. Some STM32 cortex CPU's are sold as having 64kB flash, but actually have 128kB flash. The STM32 CPU's I've always used do.

**Comment by reppad** [comment]
The famous STM32F103C**8**T6 that is in fact an STM32F103C**B**T6, my experience with bluepill boards with clone chips make me think it's even a huge MIGHT

**Comment by reppad** [comment]
To return to the loading of parameters in RAM I have to check but I think it's like that on the RT-890 OEFW stock (otherwise I'll steal you the idea 😈)
Thank you for these explanations !
