### ISSUE TITLE
Non-Issue/Info - BK4819 Datasheet

### ISSUE THREAD

**Issue by wrcrooks** [OneOfEleven/uv-k5-firmware-custom#293]
Not sure if you have this yet or not, but it looks like it "fell off the truck," so to speak.

https://prkele.prk.tky.fi/~ftg/files/datasheets/BK4819(V3)%20Application%20Note%2020210428_machine_translated_English.pdf

**Comment by OneOfEleven** [comment]
Yes I had that, thank you though. Any info is useful
