### ISSUE TITLE
Aircopy is broken ('vfo_info_t' has no membe r named 'band')

### ISSUE THREAD

**Issue by LZ2DMV** [OneOfEleven/uv-k5-firmware-custom#296]
Hey 11,

I'm glad that you are still around and i appreciate it. :)

Some of the latest changes probably broke Aircopy, because when i try to compile with it, i get:

`app/aircopy.c: In function 'AIRCOPY_Key_DIGITS':
app/aircopy.c:696:13: error: 'vfo_info_t' has no membe
r named 'band'
  696 |     g_rx_vfo->band = i;
      |             ^~
make: *** [Makefile:526: app/aircopy.o] Error 1`

**Comment by OneOfEleven** [comment]
Fixed !

Thank you for letting me know. Hope all's well.
