### ISSUE TITLE
Not an Issue - New Official Firmware Released

### ISSUE THREAD

**Issue by mjwgeek** [OneOfEleven/uv-k5-firmware-custom#299]
http://files.qsfj.com/UV-K5%20Firmware%20V31.zip?download

In case it's worth dissecting

**Comment by mjwgeek** [comment]
I guess this has been out for a couple months, so I'm closing.

**Comment by OneOfEleven** [comment]
I don't do any dissecting or disassembly, hurts my brain. DualTachyon likes it though.

**Comment by DualTachyon** [comment]
Besides, the v2.0.31 branch in my repo already has the differences/changes from .27 to .31.

**Comment by mjwgeek** [comment]
What are the important differences?
