### ISSUE TITLE
Incorrect frequency reading on the 11m band

### ISSUE THREAD

**Issue by Drevenezelezo** [OneOfEleven/uv-k5-firmware-custom#300]
Hello.  When displayed in the EU CB band on the main screen, the frequency 108Mhz is displayed on all channels.  However, the frequency is correct in the 20.56 menu.  The last version where it worked correctly was from 19.10. I don't understand programming at all, please don't take it as criticism :) This is just an observation of an ordinary user who appreciates your work.

![20231102_191117](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/149717405/1f62a3b2-a327-48d7-86a8-185694d300af)
![20231102_191221](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/149717405/d76fb14f-ec8e-4c25-a044-f17f92591e70)

**Comment by OneOfEleven** [comment]
Looks like a problem with your windows programming software, I've seen it before with the QS software and chirp. They don't recognise 27MHz as being a valid frequency and so mess up.

Your only choice is to edit the channels on the radio itself - tedious and long winded but not much choice.

I can maybe add some code in the firmware to check each channel at boot-up to ensure the band and channel match up.

**Comment by OneOfEleven** [comment]
Try the firmware now, you'll need to re-upload your channels from the PC after uploading the new firmware.

**Comment by Drevenezelezo** [comment]
After uploading the firmware, the frequencies are displayed correctly.  Thank you 🙂
