### ISSUE TITLE
Narrow mode constant noise

### ISSUE THREAD

**Issue by tevevizor** [OneOfEleven/uv-k5-firmware-custom#305]
Check videos below

https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/14348388/68fcb9e7-b9b2-4e83-863c-954e43756585

https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/14348388/8e0bd813-0f43-49b8-8d2d-2dfe244af70e

**Comment by OneOfEleven** [comment]
You need to start using a higher squelch level, the squelch is quite sensitive now.

**Comment by tevevizor** [comment]
Yes that was it actually, sorry, my bad.
At SQL level 4 it's silent.

How come noise breaks the squelch tho?

**Comment by OneOfEleven** [comment]
I don't know the complete algorithm the BK chip uses for squelch decisions, but bandwidth plays a part in it.
