### ISSUE TITLE
Scan list 1 and list 2 has damaged/overlapped fonts

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#32]
Scan list 1 and list 2 has damaged/overlapped fonts. Item 34.53 and 35.53 in the menu. Overlapped fonts are visible when defined scan list ha different in width channels names. You have to try to view that list to see the issue. The issue was seen earlier. On today's build 230921 it is still occuring

**Comment by OneOfEleven** [comment]
Someone will have to take a photo as I'm not seeing anything wrong when I go to those menu items.

**Comment by pawol** [comment]
![overlapped](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/13277626/79b1ac05-937f-4208-9e3b-55ff25d41206)

**Comment by pawol** [comment]
In the above picture it should be PLKR1 name only but we see some overlapped entry

**Comment by pawol** [comment]
I found it depends on ently lenght. 5 characters in the name makes overlapping, 6 characters is dispaeyed properly

**Comment by OneOfEleven** [comment]
ah, you must have priority channels setup.

Hopefully fixed by making the channel name small font (if need be). Let me know if still a problem or not.

**Comment by OneOfEleven** [comment]
Is it fixed for you ?

**Comment by pawol** [comment]
I shall check tomorrow

**Comment by pawol** [comment]
I hereby confirm that bux is fixed on the build 3fb5817. 
The ticket can be closed.
