### ISSUE TITLE
Compilation error when building with certain options enabled

### ISSUE THREAD

**Issue by LZ2DMV** [OneOfEleven/uv-k5-firmware-custom#48]
When building with ENABLE_VOICE, ENABLE_ALARM, ENABLE_SHOW_CHARGE_LEVEL and ENABLE_SQUELCH1_LOWER enabled, along with the options enabled by default, the build fails.

Attached are the output of gcc and the Makefile i'm using.

[output.txt](https://github.com/OneOfEleven/uv-k5-firmware-custom/files/12721156/output.txt)
[Makefile.txt](https://github.com/OneOfEleven/uv-k5-firmware-custom/files/12721158/Makefile.txt)

**Comment by OneOfEleven** [comment]
I missed a '{' in the menulist table when ENABLE_ALARM is enabled.

Fixed it now, thank you for letting me know LZ2DMV.
