### ISSUE TITLE
On the latest build b0794ec a DTMF  is decoded on screen during FM transmission

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#55]
On the latest build b0794ec some DTMF characters are decoded on screen during FM transmission reception. Some random characters happen on screen. Earlier there was not problem with that issue

**Comment by OneOfEleven** [comment]
Disable the DTMF decoder - it's the D-LIVE menu option.

**Comment by OneOfEleven** [comment]
The DTMF decoder does sometimes see voice as a DTMF character, without detailed BK4819 chip register details I can't adjust the decoder config, assuming it's possible.
Only other option is to turn the live decoder off via the D-LIVE menu option.
