### ISSUE TITLE
Recepção foi prejudicada.

### ISSUE THREAD

**Issue by marciolimapix** [OneOfEleven/uv-k5-firmware-custom#59]
Após instalação do firmware a recepção foi prejudicada, principalmente próximo aos 260MHz. Observei também que antes da atualização,  o squelch abria com -131 dBm , tanto em AM quanto FM ...  após a atualização,  o squelch ficou mais pesado , abre com - 121dBm em AM e - 117dBm em FM.

**Comment by pawol** [comment]
To be honest I am in doubt that someone will be eager to translate your laguage if you do not want even try to write in english.

Para ser sincero, tenho dúvidas de que alguém esteja ansioso para traduzir seu idioma se você não quiser nem tentar escrever em inglês.

**Comment by OneOfEleven** [comment]
I was going to answer but I wanted to check the radios specifications first. I think 260MHz is way way out of specification, in which the radio WILL be insensitive.

**Comment by OneOfEleven** [comment]
oh, ignore that, it is suppose to be OK there. Anyway, I have other bugs to sort out first. A bit overloaded with stuff at the moment.
