### ISSUE TITLE
LED Customisation suggestion

### ISSUE THREAD

**Issue by lohtse** [OneOfEleven/uv-k5-firmware-custom#60]
Is it Possible to change the LED light and function

EG Instead of Red for transmission it could be the Blue??

Just curious

**Comment by OneOfEleven** [comment]
I'm currently trying to find how the blue LED is turned on, but no luck so far.

I can see the red and green pin details but not the blue.

**Comment by LZ2DMV** [comment]
I think the blue LED cannot be controlled from software with the GPIO system. It is connected to the charging circuit on the hardware level.

**Comment by OneOfEleven** [comment]
Yes seems that way.

**Comment by lohtse** [comment]
> I think the blue LED cannot be controlled from software with the GPIO system. It is connected to the charging circuit on the hardware level.

I would disagree somewhat as it comes one when you connect the programming cable as well

**Comment by LZ2DMV** [comment]
> > I think the blue LED cannot be controlled from software with the GPIO system. It is connected to the charging circuit on the hardware level.
> 
> I would disagree somewhat as it comes one when you connect the programming cable as well

The CH340 in the cable supplies 5 V that is fed into the charging circuit at some point, that's why. Poor design by Quansheng.

**Comment by lohtse** [comment]
> > > I think the blue LED cannot be controlled from software with the GPIO system. It is connected to the charging circuit on the hardware level.
> > 
> > 
> > I would disagree somewhat as it comes one when you connect the programming cable as well
> 
> The CH340 in the cable supplies 5 V that are fed into the charging circuit at some point, that's why. Poor design by Quansheng.

OK I will accept what you are saying.but still hope for a possible solution

**Comment by wrcrooks** [comment]
The wiki has where the LEDs are connected to.

https://github.com/ludwich66/Quansheng_UV-K5_Wiki/raw/main/hardware/Block_Diagram/Quansheng_UV-K5_Block_Diagram_v01.jpg

**Comment by OneOfEleven** [comment]
Thank you for the block diagram.

The blue LED comes on and also a non-existent USB charger is detected when an external PTT is pressed when the squelch is open :(

**Comment by OneOfEleven** [comment]
Really need a full schematic to find that one I think.
