### ISSUE TITLE
Disallow entering frequencies 630-840MHz

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#61]
BK chipset has some gap in supported frequencies. If I remember it is 630-840MHz. It should not be possible to enter that range of frequencies into VFO

**Comment by lohtse** [comment]
that is correct

**Comment by OneOfEleven** [comment]
Seems to do be 630MHz to 757MHz'ish

I'll put a block on that range so the user can't set it there.

**Comment by OneOfEleven** [comment]
The datasheet says 18~660 and 840~1300, but it stops at 630MHz, restarts around ~757MHz, very insensitive but then that's to be expected.

**Comment by wrcrooks** [comment]
"World wide band: 18 MHz ~ 660 MHz, 840 MHz ~1300 MHz" - Datasheet

https://prkele.prk.tky.fi/~ftg/files/datasheets/BK4819_Datasheet_V1.01.pdf

**Comment by OneOfEleven** [comment]
can't enter above 999.999 anyway

**Comment by wrcrooks** [comment]
> can't enter above 999.999 anyway

Is that a UI limitation?

**Comment by OneOfEleven** [comment]
yes

**Comment by lohtse** [comment]
> can't enter above 999.999 anyway

yes you can, you have to use up and down to enter the frq after 999.9999

**Comment by OneOfEleven** [comment]
oh yeah lol

never knew that !

**Comment by OneOfEleven** [comment]
take it up to 1300. let me know what happens ;)

**Comment by lohtse** [comment]
> oh yeah lol
> 
> never knew that !

Even I am still learning lol

**Comment by wrcrooks** [comment]
Can we shrink the frequency text on the UI and increase the variable size to allow for >1GHz input?

**Comment by lohtse** [comment]
> Can we shrink the frequency text on the UI and increase the variable size to allow for >1GHz input?

Something I was thinking too... Differnt text sizes(like Fagci's)  and even different fonts

**Comment by OneOfEleven** [comment]
I'll let you design the slightly smaller font ;)  .. I did the small font but your turn for the bigger font

**Comment by OneOfEleven** [comment]
fonts take up a lot of flash bytes

**Comment by lohtse** [comment]
> I'll let you design the slightly smaller font ;) .. I did the small font but your turn for the bigger font

I prefer smaller text...makes tthings seem less crowded etc

**Comment by lohtse** [comment]
you ever notice that your FW is never rebooted by k5prog_wn after flashing?

**Comment by wrcrooks** [comment]
I haven't reviewed but there might not be any sub-1GHz checks in the code, it might just be that it places the first digit entered using the keypad in the _00.0000 place (100s of MHz)

**Comment by OneOfEleven** [comment]
> you ever notice that your FW is never rebooted by k5prog_wn after flashing?

yes. I keep meaning to look into that

**Comment by wrcrooks** [comment]
> you ever notice that your FW is never rebooted by k5prog_wn after flashing?

It reboots when I use the linux executable of k5prog

**Comment by OneOfEleven** [comment]
I've been distracted by getting the AM fix 100% for past how ever days, and fixing the odd bug

**Comment by OneOfEleven** [comment]
IT checks now, it will no longer allow less than 18MHz or between 630 to 757, I need to stop the user using the up/down buttons to bypass direct freq entry

**Comment by OneOfEleven** [comment]
OK, I've uploaded new firmware that stops user going into the 630 to 757MHz range.

**Comment by OneOfEleven** [comment]
> you ever notice that your FW is never rebooted by k5prog_wn after flashing?

I think I got it now. It should reboot the radio OK - let me know if it don't

**Comment by pawol** [comment]
Now when I put 650.000MHz into VFO then frequency is changed onto 630.000MHz. If I know 630 is forbidden also. When I use arrows then maximum frequency is 629,99375 (below 630 as we see)

**Comment by lohtse** [comment]
> > you ever notice that your FW is never rebooted by k5prog_wn after flashing?
> 
> I think I got it now. It should reboot the radio OK - let me know if it don't

It does...

**Comment by OneOfEleven** [comment]
> Now when I put 650.000MHz into VFO then frequency is changed onto 630.000MHz. It is almost right behaviour. If I know 630 is forbidden also on BK. When I use arrows then maximum frequency is 629,99375 (below 630 as we see).
> 
> I see also that upper limit is set on 760MHz. Is it right? Wer talked about 757MHz at the beginning

Yes I was lazy last night and decided not to check the current frequency step value to choose the correct frequency to limit/actually use (instead of 630 or 629,99375).

I'll do that today, was a busy day yesterday.

**Comment by OneOfEleven** [comment]
But yes, 630 is the chip won't do, so I need to just subtract the current frequency step value from 630 and limit it to there. I also chose 760MHz rather than 757, just to round it up a bit, Makes no odds really cuz the radio is as deaf as a stone there.

**Comment by OneOfEleven** [comment]
OK, think I got it right now. Just uploaded.

**Comment by pawol** [comment]
Upper limit is 757 or 760 ?

**Comment by OneOfEleven** [comment]
I've gone for 840MHz as per datasheet, but I found the PLL starts to lock around 757MHz'ish

**Comment by pawol** [comment]
Ticket can be closed because the fix works as expected
