### ISSUE TITLE
edit frecuency in Scramble menu

### ISSUE THREAD

**Issue by Yag00000** [OneOfEleven/uv-k5-firmware-custom#63]
edit new frecuency in scramble menu

**Comment by OneOfEleven** [comment]
I don't think the BK4819 chip allows for any other scramble frequencies, it seems to allow only the ones listed.

**Comment by OneOfEleven** [comment]
But together with the radios built-in FSK modem, a rolling code scrambler can be written - short burst of FSK data at start of each TX syncs the scramblers in all radios on channel, just like motorola do.

**Comment by Yag00000** [comment]
fantastic !!!!!
