### ISSUE TITLE
Rssi sbar not work

### ISSUE THREAD

**Issue by Braccato** [OneOfEleven/uv-k5-firmware-custom#71]
since I installed the latest firmware with the rssi bar the display has been damaged.
i tested K5, K6, 5Rplus

https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/141162772/15399f5e-4738-40f9-86d6-167ca48955e9

**Comment by lohtse** [comment]
I suggest you go to telegram group as this is a KNOWN issue.

**Comment by Braccato** [comment]
link telegram please

**Comment by OneOfEleven** [comment]
That doesn't look good !

Looks like a hardware problem there, maybe dropped the radio or something ?

**Comment by lohtse** [comment]
https://t.me/quansheng_uvk5_en

**Comment by Braccato** [comment]
the radio is new, I also tested it on the k5 and the 5R_plus, it has the same defect

**Comment by lohtse** [comment]
> the radio is new, I also tested it on the k5 and the 5R_plus, it has the same defect

NOT a DEFECT a bug.. And now I remember who you are...

**Comment by lohtse** [comment]
there was another member on telegram who did the same to produce the bug... literally the only way it happens is when they do the same covering up and pressing buttons at the same time.

**Comment by lohtse** [comment]
I would close this as it is not anb  issue with your FW.

**Comment by OneOfEleven** [comment]
That's a design problem with the radio, RF getting into where you don't want it too.

**Comment by Braccato** [comment]
it is a flaw of all rssi sbar, you have to find a solution, even with pietr022's rssi sbar it does it

**Comment by OneOfEleven** [comment]
Nothing I can do, it's an RF problem.

**Comment by lohtse** [comment]
> it is a flaw of all rssi sbar, you have to find a solution, even with pietr022's rssi sbar it does it

Yes TORRE JOHN... hell why don't YOU FIX IT

**Comment by OneOfEleven** [comment]
Some decoupling caps places in some suitable positions on the PCB might help, but I'll leave that up to everyone else.
