### ISSUE TITLE
On commit c3c344d sometime tx is allowed when AM

### ISSUE THREAD

**Issue by pawol** [OneOfEleven/uv-k5-firmware-custom#82]
On commit c3c344d sometime tx is allowed when AM.
Just after update or QS power off/on.
Pressing of PTT does not show TX disable and red led is lit. It seems the behaviour occurs until 1st squelch opening.

**Comment by OneOfEleven** [comment]
Yes I know, I've been trying to do too many things at once,, I'll fix it shortly. Bare with me.

**Comment by pawol** [comment]
Just report you ti keep it in mind :)

**Comment by OneOfEleven** [comment]
ha. software/firmware is NEVER finished.

Just don't delete this issue, otherwise I will forget :)

**Comment by OneOfEleven** [comment]
Do you have dual-watch (Dual-RX) enabled when the problem happens ?

**Comment by lohtse** [comment]
> On commit c3c344d sometime tx is allowed when AM.
> Just after update or QS power off/on.
> Pressing of PTT does not show TX disable and red led is lit. It seems the behaviour occurs until 1st squelch opening.

I had reported this already buddy..you could have just added too that instead of starting  new issue...

**Comment by OneOfEleven** [comment]
>**It seems the behaviour occurs until 1st squelch opening.**

Thank you !   that's a key bit of info, I'll soon find that.

**Comment by pawol** [comment]
Yes, I have dual watch and active channel is set on AM

**Comment by pawol** [comment]
Since 2 commits I use lower squelch feature also

**Comment by OneOfEleven** [comment]
it's only when dual-watch is enabled. It does transmit on the FM channel not the AM channel, it's just that it shouldn't be transmitting at all when the main channel is the AM one.

**Comment by pawol** [comment]
I shall check it with standard squelch. I never noticed it earlier

**Comment by pawol** [comment]
I have checked and the issue depends only on dual watch

**Comment by OneOfEleven** [comment]
Try it now, I 'think' I've got it, though there are multiple factors that affect the TX freq/chan to take into account, my heads spinning from it.

**Comment by OneOfEleven** [comment]
no, ignore that :(

**Comment by pawol** [comment]
The issue is fixed on commit e0aa1a8. 
The ticket can be closed

**Comment by OneOfEleven** [comment]
i think there is still a funny with, I had it do it once which means I've missed something that needs finding.

**Comment by pawol** [comment]
IMHO the bug was fixed. Cannot reproduce the issue.

**Comment by OneOfEleven** [comment]
I've been changing it slightly, so let me know if the problem re-appears, or if it TX's on the wrong VFO (should only ever TX on the selected VFO - solid black triangle indicator).

**Comment by pawol** [comment]
Cannot reproduce now
