### ISSUE TITLE
[Advice] Disable OVERLAY by default to save space

### ISSUE THREAD

**Issue by LZ2DMV** [OneOfEleven/uv-k5-firmware-custom#83]
Hi OneOfEleven,

@DualTachyon just confirmed on Telegram that it is safe to disable OVERLAY by default (in the default Makefile), because the bootloader runs the same code and the settings persist between the soft resets it issues, so it is a safe thing to cut to get more space for new features.

**Comment by OneOfEleven** [comment]
Roger !

Thank you
