### ISSUE TITLE
de174d0: Deaf on AM

### ISSUE THREAD

**Issue by DE8MSH** [OneOfEleven/uv-k5-firmware-custom#95]
Hi 1O11.

From de174d0 on RX in mode AM isn't working anymore -- or let ne say 'as before'. Even very strong ATIS (weather condition) stations are very weak. What happened?

EDIT: -98dB brings bad AM demodulation again.

EDIT²: Setup SQL 2 (before 1 -- 1 gives open SQL on some freqs now even with no signal/noise only), Wide, AM fix on, Battsave 1:4.

**Comment by OneOfEleven** [comment]
If your squelch is now too sensitive, then change this line in Makefile from this ..

ENABLE_SQUELCH_LOWER := 1

to this ..

ENABLE_SQUELCH_LOWER := 0

then recompile and upload to your radio.

**Comment by OneOfEleven** [comment]
Can you do a little video of what's happening to the AM audio so I can see what the AM screen data is saying ?

**Comment by OneOfEleven** [comment]
Bare in mind that the UV-k5(8) (k6 ?) is currently down to £9.70 inc free postage/shipping on ali for some reason.
