### ISSUE TITLE
Turbo Scan 💯 *Not an issue*

### ISSUE THREAD

**Issue by M7OCM** [OneOfEleven/uv-k5-firmware-custom#96]
Wow the scan rate has risen dramatically thanks 111 :-)

**Comment by PieeerB** [comment]
It remains to make a choice of the scanning range vfo1-vfo2

**Comment by OneOfEleven** [comment]
> Wow the scan rate has risen dramatically thanks 111 :-)

So long as it's not to fast so as to miss signals, it takes time for the PLL to lock and for the squelch to open/respond, but I've been testing difference speeds to find the 'just to fast' threshold (around 50ms per channel is the fastest really)., then almost double the time spent (80ms actually) on each channel just to be sure it's OK.

**Comment by OneOfEleven** [comment]
> It remains to make a choice of the scanning range vfo1-vfo2

Bug fixes before adding anything else I think.

**Comment by M7OCM** [comment]
> > Wow the scan rate has risen dramatically thanks 111 :-)
> 
> So long as it's not to fast so as to miss signals, it takes time for the PLL to lock and for the squelch to open/respond, but I've been testing difference speeds to find the 'just to fast' threshold (around 50ms per channel is the fastest really)., then almost double the time spent (80ms actually) on each channel just to be sure it's OK.

Yes understandable, hit a station straight away so seems to be perfect 111. Well done.

**Comment by PieeerB** [comment]
are there any plans to make a scanning range??

**Comment by OneOfEleven** [comment]
I'm sure someone might in time. I'm not sure how much longer I shall continue myself., I've done a lot to add too the project.

**Comment by OneOfEleven** [comment]
I've only increased the channel scanning speed at the moment. I want to increase the frequency scan speed too (scanning across a frequency band).

**Comment by lohtse** [comment]
> I've only increased the channel scanning speed at the moment. I want to increase the frequency scan speed too (scanning across a frequency band).

now that would be awesome!!!

**Comment by DE8MSH** [comment]
Scanning by 1O11:

https://www.youtube.com/shorts/_YZS4t4G9Us

**Comment by OneOfEleven** [comment]
Making it scan faster means making the squelch open/close faster in order to keep up, but the side effect is a twitchy squelch (flashy green LED).
